name: molscribe
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch::pytorch=1.*.*=*cuda*
  - pytorch::torchvision
  - pip
  - pip:
    - rdkit-pypi>=2021.03.2
    - pandas
    - matplotlib
    - tensorboardX
    - opencv-python==4.5.5.64
    - transformers>=4.5.1
    - SmilesPE==0.0.3
    - OpenNMT-py==2.2.0
    - albumentations==1.1.0
    - timm==0.5.4
